raise Error('The casa commands log is not executable!')

# # This file contains CASA commands run by the pipeline. Although all
# commands required to calibrate the data are included here, this file cannot
# be executed, nor does it contain heuristic and flagging calculations
# performed by pipeline code. This file is useful to understand which CASA
# commands are being run by each pipeline task. If one wishes to re-run the
# pipeline, one should use the pipeline script linked on the front page of the
# weblog. Some stages may not have any commands listed here, e.g.
# hifa_importdata if conversion from ASDM to MS is not required.

# hifa_importdata(dbservice=False, vis=['uid___A002_Xa48b1f_X3ca7', 'uid___A002_Xa4ce71_X1356'], session=['session_1', 'session_2'])
#
# If required, ASDMs are converted to measurement sets.
#
importasdm(outfile='uid___A002_Xa48b1f_X3ca7_flagonline.txt', ocorr_mode='ca',
           process_caldevice=False, vis='uid___A002_Xa48b1f_X3ca7.ms',
           asdm='/mnt/jaosco/pipeline/data/2013.1.00059.S_2015_10_14T14_00_32.535/SOUS_uid___A001_X12b_X239/GOUS_uid___A001_X12b_X23a/MOUS_uid___A001_X12b_X23b/rawdata/uid___A002_Xa48b1f_X3ca7',
           savecmds=True, bdfflags=True, asis='Antenna Station Receiver Source
           CalAtmosphere CalWVR', overwrite=False)
importasdm(outfile='uid___A002_Xa4ce71_X1356_flagonline.txt', ocorr_mode='ca',
           process_caldevice=False, vis='uid___A002_Xa4ce71_X1356.ms',
           asdm='/mnt/jaosco/pipeline/data/2013.1.00059.S_2015_10_14T14_00_32.535/SOUS_uid___A001_X12b_X239/GOUS_uid___A001_X12b_X23a/MOUS_uid___A001_X12b_X23b/rawdata/uid___A002_Xa4ce71_X1356',
           savecmds=True, bdfflags=True, asis='Antenna Station Receiver Source
           CalAtmosphere CalWVR', overwrite=False)

# hifa_flagdata(pipelinemode="automatic")
#
# Flags generated by the online telescope software, by the QA0 process, and
# manually set by the pipeline user.
#
flagdata(tbuff=2.976, flagbackup=False, vis='uid___A002_Xa48b1f_X3ca7.ms',
         mode='list', action='apply', savepars=False,
         inpfile='uid___A002_Xa48b1f_X3ca7_flagcmds.txt')
flagdata(tbuff=2.976, flagbackup=False, vis='uid___A002_Xa4ce71_X1356.ms',
         mode='list', action='apply', savepars=False,
         inpfile='uid___A002_Xa4ce71_X1356_flagcmds.txt')

# hifa_fluxcalflag(pipelinemode="automatic")
#
# This stage performs a pipeline calculation without running any CASA commands
# to be put in this file.
#

# hif_rawflagchans(pipelinemode="automatic")
#
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms', mode='summary', name='before')
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms', mode='summary', name='after')
flagdata(vis='uid___A002_Xa4ce71_X1356.ms', mode='summary', name='before')
flagdata(vis='uid___A002_Xa4ce71_X1356.ms', mode='summary', name='after')

# hif_refant(pipelinemode="automatic")
#
# Antennas are prioritized and enumerated based on fraction flagged and
# position in the array. The best antenna is used as a reference antenna
# unless it gets flagged, in which case the next-best antenna is used. This
# stage performs a pipeline calculation without running any CASA commands to
# be put in this file.
#

# hifa_tsyscal(pipelinemode="automatic")
#
# The Tsys calibration and spectral window map is computed.
#
gencal(caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
       vis='uid___A002_Xa48b1f_X3ca7.ms', caltype='tsys')
gencal(caltable='uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
       vis='uid___A002_Xa4ce71_X1356.ms', caltype='tsys')

# hifa_tsysflag(pipelinemode="automatic")
#
# The Tsys calibration table is analyzed and deviant points are flagged.
#
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         mode='summary')
flagdata(flagbackup=False,
         vis='uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         reason='any', mode='list', action='apply', savepars=False,
         inpfile=["reason='edges' spw='11:0~4'", "reason='edges' spw='13:0~4'",
         "reason='edges' spw='15:0~2'", "reason='edges' spw='9:0~4'",
         "reason='edges' spw='11:0~4'", "reason='edges' spw='13:0~4'",
         "reason='edges' spw='15:0~2'", "reason='edges' spw='9:0~4'",
         "reason='edges' spw='11:0~4'", "reason='edges' spw='13:0~4'",
         "reason='edges' spw='15:0~1'", "reason='edges' spw='9:0~4'"])
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         mode='summary')
flagdata(flagbackup=False,
         vis='uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         reason='any', mode='list', action='apply', savepars=False,
         inpfile=["reason='sharps' spw='11:5~19' antenna='23'", "reason='sharps'
         spw='9:96~105' antenna='38'"])
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         mode='summary')
flagdata(flagbackup=False,
         vis='uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         reason='any', mode='list', action='apply', savepars=False,
         inpfile=["reason='edges' spw='11:0~4'", "reason='edges' spw='13:0~4'",
         "reason='edges' spw='15:0~2'", "reason='edges' spw='9:0~5'",
         "reason='edges' spw='11:0~4'", "reason='edges' spw='13:0~4'",
         "reason='edges' spw='15:0~1'", "reason='edges' spw='9:0~4'",
         "reason='edges' spw='11:0~4'", "reason='edges' spw='13:0~4'",
         "reason='edges' spw='15:0~1'", "reason='edges' spw='9:0~4'"])
flagdata(vis='uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         mode='summary')
flagdata(flagbackup=False,
         vis='uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         reason='any', mode='list', action='apply', savepars=False,
         inpfile=["reason='sharps' spw='11:5~19' antenna='24'", "reason='sharps'
         spw='15:3~9' antenna='9'"])
flagdata(vis='uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         mode='summary')
flagdata(vis='uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         mode='summary')

# hifa_wvrgcalflag(pipelinemode="automatic")
#
# Water vapour radiometer corrections are calculated for each antenna. The
# quality of the correction is assessed by comparing a phase gain solution
# calculated with and without the WVR correction. This requires calculation of
# a temporary phase gain on the bandpass calibrator, a temporary bandpass
# using that temporary gain, followed by phase gains with the temporary
# bandpass, with and without the WVR correction. After that, some antennas are
# wvrflagged (so that their WVR corrections are interpolated), and then the
# quality of the correction recalculated.
#
wvrgcal(scale=1.0, nsol=1, segsource=True, sourceflag=[],
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
        smooth='6.048s', spw=[17, 19, 21, 23],
        vis='uid___A002_Xa48b1f_X3ca7.ms', wvrspw=[0], mingoodfrac=0.8,
        disperse=False, maxdistm=500.0, minnumants=2, tie=['J0010+1058,BX610'],
        toffset=0, wvrflag=[])
gaincal(field='J2232+1143', minblperant=4, antenna='0~41', solint='int',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_6.spw19.solintint.gpcal.tbl',
        interp='linear,linear', minsnr=3.0,
        gaintable='uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        spw='19', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='p', gaintype='G',
        spwmap=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
        11, 11, 13, 13, 15, 15], intent='*BANDPASS*', solnorm=False,
        refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield='nearest')
bandpass(field='J2232+1143', bandtype='B', antenna='0~41',
         solint='inf,7.8125MHz',
         caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_7.spw19.channel.solintinf_7_812MHz.bcal.tbl',
         interp=['linear,linear', 'linear,linear'], minsnr=3.0,
         gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_6.spw19.solintint.gpcal.tbl'],
         spw='19', vis='uid___A002_Xa48b1f_X3ca7.ms', combine='scan',
         spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
         11, 11, 13, 13, 15, 15], []], intent='*BANDPASS*', solnorm=True,
         refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
         gainfield=['nearest', 'nearest'], minblperant=4)
gaincal(field='J0010+1058,J2232+1143', minblperant=4, antenna='0~41',
        solint='int',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_5.spw19.solintint.gpcal.nowvr.tbl',
        interp=['linear,linear', 'linearperobs,linearflag'], minsnr=0.0,
        gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_7.spw19.channel.solintinf_7_812MHz.bcal.tbl'],
        spw='19', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='p', gaintype='G',
        spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
        11, 11, 13, 13, 15, 15], []], intent='*PHASE*,*BANDPASS*',
        solnorm=False,
        refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', ''])
gaincal(field='J0010+1058,J2232+1143', minblperant=4, antenna='0~41',
        solint='int',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_6.spw19.solintint.gpcal.wvr.tbl',
        interp=['linear,linear', 'linearperobs,linearflag', 'nearest'],
        minsnr=0.0,
        gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_7.spw19.channel.solintinf_7_812MHz.bcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl'],
        spw='19', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='p', gaintype='G',
        spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
        11, 11, 13, 13, 15, 15], [], []], intent='*PHASE*,*BANDPASS*',
        solnorm=False,
        refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', ''])
wvrgcal(scale=1.0, nsol=1, segsource=True, sourceflag=[],
        caltable='uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_6.sm6_048s.wvrcal.tbl',
        smooth='6.048s', spw=[17, 19, 21, 23],
        vis='uid___A002_Xa4ce71_X1356.ms', wvrspw=[0], mingoodfrac=0.8,
        disperse=False, maxdistm=500.0, minnumants=2, tie=['J0010+1058,BX610'],
        toffset=0, wvrflag=[])
gaincal(field='J2232+1143', minblperant=4, antenna='0~42', solint='int',
        caltable='uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.spw19.solintint.gpcal.tbl',
        interp='linear,linear', minsnr=3.0,
        gaintable='uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
        spw='19', vis='uid___A002_Xa4ce71_X1356.ms', calmode='p', gaintype='G',
        spwmap=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
        11, 11, 13, 13, 15, 15], intent='*BANDPASS*', solnorm=False,
        refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA55,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DA43,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield='nearest')
bandpass(field='J2232+1143', bandtype='B', antenna='0~42',
         solint='inf,7.8125MHz',
         caltable='uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_9.spw19.channel.solintinf_7_812MHz.bcal.tbl',
         interp=['linear,linear', 'linear,linear'], minsnr=3.0,
         gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.spw19.solintint.gpcal.tbl'],
         spw='19', vis='uid___A002_Xa4ce71_X1356.ms', combine='scan',
         spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
         11, 11, 13, 13, 15, 15], []], intent='*BANDPASS*', solnorm=True,
         refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA55,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DA43,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
         gainfield=['nearest', 'nearest'], minblperant=4)
gaincal(field='J0010+1058,J2232+1143', minblperant=4, antenna='0~42',
        solint='int',
        caltable='uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_7.spw19.solintint.gpcal.nowvr.tbl',
        interp=['linear,linear', 'linearperobs,linearflag'], minsnr=0.0,
        gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_9.spw19.channel.solintinf_7_812MHz.bcal.tbl'],
        spw='19', vis='uid___A002_Xa4ce71_X1356.ms', calmode='p', gaintype='G',
        spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
        11, 11, 13, 13, 15, 15], []], intent='*PHASE*,*BANDPASS*',
        solnorm=False,
        refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA55,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DA43,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', ''])
gaincal(field='J0010+1058,J2232+1143', minblperant=4, antenna='0~42',
        solint='int',
        caltable='uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.spw19.solintint.gpcal.wvr.tbl',
        interp=['linear,linear', 'linearperobs,linearflag', 'nearest'],
        minsnr=0.0,
        gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_9.spw19.channel.solintinf_7_812MHz.bcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_6.sm6_048s.wvrcal.tbl'],
        spw='19', vis='uid___A002_Xa4ce71_X1356.ms', calmode='p', gaintype='G',
        spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
        11, 11, 13, 13, 15, 15], [], []], intent='*PHASE*,*BANDPASS*',
        solnorm=False,
        refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA55,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DA43,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', ''])
wvrgcal(scale=1.0, nsol=1, segsource=True, sourceflag=[],
        caltable='uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
        smooth='6.048s', spw=[17, 19, 21, 23],
        vis='uid___A002_Xa4ce71_X1356.ms', wvrspw=[0], mingoodfrac=0.8,
        disperse=False, maxdistm=500.0, minnumants=2, tie=['J0010+1058,BX610'],
        toffset=0, wvrflag=['DA43', 'DA55'])
gaincal(field='J0010+1058,J2232+1143', minblperant=4, antenna='0~42',
        solint='int',
        caltable='uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.spw19.solintint.gpcal.flagged_2_antennas.wvr.tbl',
        interp=['linear,linear', 'linearperobs,linearflag', 'nearest'],
        minsnr=0.0,
        gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_9.spw19.channel.solintinf_7_812MHz.bcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl'],
        spw='19', vis='uid___A002_Xa4ce71_X1356.ms', calmode='p', gaintype='G',
        spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
        11, 11, 13, 13, 15, 15], [], []], intent='*PHASE*,*BANDPASS*',
        solnorm=False,
        refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', ''])

# hif_lowgainflag(pipelinemode="automatic")
#
# Sometimes antennas have significantly lower gain than nominal. Even when
# calibrated, it is better for ALMA data to flag these antennas. The pipeline
# detects this by calculating a long solint amplitude gain on the bandpass
# calibrator.  First, temporary phase and bandpass solutions are calculated,
# and then that temporary bandpass is used to calculate a short solint phase
# and long solint amplitude solution.
#
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms', mode='summary')
gaincal(field='J2232+1143', minblperant=4, antenna='0~41', solint='int',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hif_lowgainflag.s9_5.spw17_19_21_23.solintint.gpcal.tbl',
        interp=['linear,linear', 'nearest'], minsnr=3.0,
        gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], []], intent='*BANDPASS*',
        solnorm=False,
        refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', ''])
bandpass(field='J2232+1143', bandtype='B', antenna='0~41',
         solint='inf,7.8125MHz',
         caltable='uid___A002_Xa48b1f_X3ca7.ms.hif_lowgainflag.s9_6.spw17_19_21_23.channel.solintinf_7_812MHz.bcal.tbl',
         interp=['linear,linear', 'nearest', 'linear,linear'], minsnr=3.0,
         gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hif_lowgainflag.s9_5.spw17_19_21_23.solintint.gpcal.tbl'],
         spw='17,19,21,23', vis='uid___A002_Xa48b1f_X3ca7.ms', combine='scan',
         spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
         11, 11, 13, 13, 15, 15], [], []], intent='*BANDPASS*', solnorm=True,
         refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
         gainfield=['nearest', '', 'nearest'], minblperant=4)
gaincal(field='J2232+1143', minblperant=4, antenna='0~41', solint='int',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hif_lowgainflag.s9_5.spw17_19_21_23.solintint.gpcal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag'],
        minsnr=2.0,
        gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hif_lowgainflag.s9_6.spw17_19_21_23.channel.solintinf_7_812MHz.bcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], []], intent='*BANDPASS*',
        solnorm=False,
        refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', ''])
gaincal(field='J2232+1143', minblperant=4, antenna='0~41', solint='inf',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hif_lowgainflag.s9_6.spw17_19_21_23.solintinf.gacal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
        'linear,linear'], minsnr=2.0,
        gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hif_lowgainflag.s9_6.spw17_19_21_23.channel.solintinf_7_812MHz.bcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hif_lowgainflag.s9_5.spw17_19_21_23.solintint.gpcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='a',
        gaintype='T', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], []], intent='*BANDPASS*',
        solnorm=False,
        refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', '', 'nearest'])
flagdata(flagbackup=False, vis='uid___A002_Xa48b1f_X3ca7.ms', reason='any',
         mode='list', action='apply', savepars=False, inpfile=["reason='nmedian'
         spw='17' antenna='2'", "reason='nmedian' spw='19' antenna='2'",
         "reason='nmedian' spw='21' antenna='2'", "reason='nmedian' spw='23'
         antenna='2'"])
gaincal(field='J2232+1143', minblperant=4, antenna='0~41', solint='int',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hif_lowgainflag.s9_7.spw17_19_21_23.solintint.gpcal.tbl',
        interp=['linear,linear', 'nearest'], minsnr=3.0,
        gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], []], intent='*BANDPASS*',
        solnorm=False,
        refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', ''])
bandpass(field='J2232+1143', bandtype='B', antenna='0~41',
         solint='inf,7.8125MHz',
         caltable='uid___A002_Xa48b1f_X3ca7.ms.hif_lowgainflag.s9_8.spw17_19_21_23.channel.solintinf_7_812MHz.bcal.tbl',
         interp=['linear,linear', 'nearest', 'linear,linear'], minsnr=3.0,
         gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hif_lowgainflag.s9_7.spw17_19_21_23.solintint.gpcal.tbl'],
         spw='17,19,21,23', vis='uid___A002_Xa48b1f_X3ca7.ms', combine='scan',
         spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
         11, 11, 13, 13, 15, 15], [], []], intent='*BANDPASS*', solnorm=True,
         refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
         gainfield=['nearest', '', 'nearest'], minblperant=4)
gaincal(field='J2232+1143', minblperant=4, antenna='0~41', solint='int',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hif_lowgainflag.s9_7.spw17_19_21_23.solintint.gpcal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag'],
        minsnr=2.0,
        gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hif_lowgainflag.s9_8.spw17_19_21_23.channel.solintinf_7_812MHz.bcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], []], intent='*BANDPASS*',
        solnorm=False,
        refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', ''])
gaincal(field='J2232+1143', minblperant=4, antenna='0~41', solint='inf',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hif_lowgainflag.s9_8.spw17_19_21_23.solintinf.gacal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
        'linear,linear'], minsnr=2.0,
        gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hif_lowgainflag.s9_8.spw17_19_21_23.channel.solintinf_7_812MHz.bcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hif_lowgainflag.s9_7.spw17_19_21_23.solintint.gpcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='a',
        gaintype='T', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], []], intent='*BANDPASS*',
        solnorm=False,
        refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', '', 'nearest'])
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms', mode='summary')
flagdata(vis='uid___A002_Xa4ce71_X1356.ms', mode='summary')
gaincal(field='J2232+1143', minblperant=4, antenna='0~42', solint='int',
        caltable='uid___A002_Xa4ce71_X1356.ms.hif_lowgainflag.s9_7.spw17_19_21_23.solintint.gpcal.tbl',
        interp=['linear,linear', 'nearest'], minsnr=3.0,
        gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa4ce71_X1356.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], []], intent='*BANDPASS*',
        solnorm=False,
        refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', ''])
bandpass(field='J2232+1143', bandtype='B', antenna='0~42',
         solint='inf,7.8125MHz',
         caltable='uid___A002_Xa4ce71_X1356.ms.hif_lowgainflag.s9_8.spw17_19_21_23.channel.solintinf_7_812MHz.bcal.tbl',
         interp=['linear,linear', 'nearest', 'linear,linear'], minsnr=3.0,
         gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hif_lowgainflag.s9_7.spw17_19_21_23.solintint.gpcal.tbl'],
         spw='17,19,21,23', vis='uid___A002_Xa4ce71_X1356.ms', combine='scan',
         spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
         11, 11, 13, 13, 15, 15], [], []], intent='*BANDPASS*', solnorm=True,
         refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
         gainfield=['nearest', '', 'nearest'], minblperant=4)
gaincal(field='J2232+1143', minblperant=4, antenna='0~42', solint='int',
        caltable='uid___A002_Xa4ce71_X1356.ms.hif_lowgainflag.s9_7.spw17_19_21_23.solintint.gpcal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag'],
        minsnr=2.0,
        gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hif_lowgainflag.s9_8.spw17_19_21_23.channel.solintinf_7_812MHz.bcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa4ce71_X1356.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], []], intent='*BANDPASS*',
        solnorm=False,
        refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', ''])
gaincal(field='J2232+1143', minblperant=4, antenna='0~42', solint='inf',
        caltable='uid___A002_Xa4ce71_X1356.ms.hif_lowgainflag.s9_8.spw17_19_21_23.solintinf.gacal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
        'linear,linear'], minsnr=2.0,
        gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hif_lowgainflag.s9_8.spw17_19_21_23.channel.solintinf_7_812MHz.bcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hif_lowgainflag.s9_7.spw17_19_21_23.solintint.gpcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa4ce71_X1356.ms', calmode='a',
        gaintype='T', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], []], intent='*BANDPASS*',
        solnorm=False,
        refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', '', 'nearest'])
flagdata(vis='uid___A002_Xa4ce71_X1356.ms', mode='summary')

# hif_setjy(pipelinemode="automatic")
#
# If the amplitude calibrator is a resolved solar system source, this uses a
# subset of antennas with short baselines (where the resolved source model is
# of highest quality).
#
post_to_log(comment='Setjy marker: 2015-10-14 15:53:37.421976',
            echo_to_screen=False)
setjy(fluxdensity=-1, scalebychan=True, vis='uid___A002_Xa48b1f_X3ca7.ms',
      spix=0.0, spw='17,19,21,23', field='Ceres', reffreq='1GHz',
      intent='*FLUX*,*AMPLI*', selectdata=True, standard='Butler-JPL-Horizons
      2012', usescratch=True)
post_to_log(comment='Setjy marker: 2015-10-14 15:59:37.665514',
            echo_to_screen=False)
post_to_log(comment='Setjy marker: 2015-10-14 15:59:40.280766',
            echo_to_screen=False)
setjy(fluxdensity=-1, scalebychan=True, vis='uid___A002_Xa4ce71_X1356.ms',
      spix=0.0, spw='17,19,21,23', field='Ceres', reffreq='1GHz',
      intent='*FLUX*,*AMPLI*', selectdata=True, standard='Butler-JPL-Horizons
      2012', usescratch=True)
post_to_log(comment='Setjy marker: 2015-10-14 16:04:39.512819',
            echo_to_screen=False)

# hifa_bandpass(pipelinemode="automatic")
#
# The spectral response of each antenna is calibrated. A short-solint phase
# gain is calculated to remove decorrelation of the bandpass calibrator before
# the bandpass is calculated.
#
gaincal(field='J2232+1143', minblperant=4, antenna='0~41', solint='int',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.solintint.gpcal.tbl',
        interp=['linear,linear', 'nearest'], minsnr=3.0,
        gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], []], intent='*BANDPASS*',
        solnorm=False,
        refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', ''])
bandpass(field='J2232+1143', bandtype='B', antenna='0~41', solint='inf,1ch',
         caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.channel.solintinf.bcal.tbl',
         interp=['linear,linear', 'nearest', 'linear,linear'], minsnr=3.0,
         gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.solintint.gpcal.tbl'],
         spw='17', vis='uid___A002_Xa48b1f_X3ca7.ms', combine='scan',
         spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
         11, 11, 13, 13, 15, 15], [], []], intent='*BANDPASS*', solnorm=True,
         refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
         gainfield=['nearest', '', 'nearest'], minblperant=4)
bandpass(field='J2232+1143', bandtype='B', antenna='0~41', solint='inf,1ch',
         caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.channel.solintinf.bcal.tbl',
         interp=['linear,linear', 'nearest', 'linear,linear'], minsnr=3.0,
         gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.solintint.gpcal.tbl'],
         spw='19', vis='uid___A002_Xa48b1f_X3ca7.ms', combine='scan',
         spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
         11, 11, 13, 13, 15, 15], [], []], intent='*BANDPASS*', solnorm=True,
         refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
         gainfield=['nearest', '', 'nearest'], append=True, minblperant=4)
bandpass(field='J2232+1143', bandtype='B', antenna='0~41', solint='inf,1ch',
         caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.channel.solintinf.bcal.tbl',
         interp=['linear,linear', 'nearest', 'linear,linear'], minsnr=3.0,
         gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.solintint.gpcal.tbl'],
         spw='21', vis='uid___A002_Xa48b1f_X3ca7.ms', combine='scan',
         spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
         11, 11, 13, 13, 15, 15], [], []], intent='*BANDPASS*', solnorm=True,
         refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
         gainfield=['nearest', '', 'nearest'], append=True, minblperant=4)
bandpass(field='J2232+1143', bandtype='B', antenna='0~41', solint='inf,1ch',
         caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.channel.solintinf.bcal.tbl',
         interp=['linear,linear', 'nearest', 'linear,linear'], minsnr=3.0,
         gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.solintint.gpcal.tbl'],
         spw='23', vis='uid___A002_Xa48b1f_X3ca7.ms', combine='scan',
         spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
         11, 11, 13, 13, 15, 15], [], []], intent='*BANDPASS*', solnorm=True,
         refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
         gainfield=['nearest', '', 'nearest'], append=True, minblperant=4)
gaincal(field='J2232+1143', minblperant=4, antenna='0~42', solint='int',
        caltable='uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.solintint.gpcal.tbl',
        interp=['linear,linear', 'nearest'], minsnr=3.0,
        gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa4ce71_X1356.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], []], intent='*BANDPASS*',
        solnorm=False,
        refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', ''])
bandpass(field='J2232+1143', bandtype='B', antenna='0~42', solint='inf,1ch',
         caltable='uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.channel.solintinf.bcal.tbl',
         interp=['linear,linear', 'nearest', 'linear,linear'], minsnr=3.0,
         gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.solintint.gpcal.tbl'],
         spw='17', vis='uid___A002_Xa4ce71_X1356.ms', combine='scan',
         spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
         11, 11, 13, 13, 15, 15], [], []], intent='*BANDPASS*', solnorm=True,
         refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
         gainfield=['nearest', '', 'nearest'], minblperant=4)
bandpass(field='J2232+1143', bandtype='B', antenna='0~42', solint='inf,1ch',
         caltable='uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.channel.solintinf.bcal.tbl',
         interp=['linear,linear', 'nearest', 'linear,linear'], minsnr=3.0,
         gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.solintint.gpcal.tbl'],
         spw='19', vis='uid___A002_Xa4ce71_X1356.ms', combine='scan',
         spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
         11, 11, 13, 13, 15, 15], [], []], intent='*BANDPASS*', solnorm=True,
         refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
         gainfield=['nearest', '', 'nearest'], append=True, minblperant=4)
bandpass(field='J2232+1143', bandtype='B', antenna='0~42', solint='inf,1ch',
         caltable='uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.channel.solintinf.bcal.tbl',
         interp=['linear,linear', 'nearest', 'linear,linear'], minsnr=3.0,
         gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.solintint.gpcal.tbl'],
         spw='21', vis='uid___A002_Xa4ce71_X1356.ms', combine='scan',
         spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
         11, 11, 13, 13, 15, 15], [], []], intent='*BANDPASS*', solnorm=True,
         refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
         gainfield=['nearest', '', 'nearest'], append=True, minblperant=4)
bandpass(field='J2232+1143', bandtype='B', antenna='0~42', solint='inf,1ch',
         caltable='uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.channel.solintinf.bcal.tbl',
         interp=['linear,linear', 'nearest', 'linear,linear'], minsnr=3.0,
         gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.solintint.gpcal.tbl'],
         spw='23', vis='uid___A002_Xa4ce71_X1356.ms', combine='scan',
         spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
         11, 11, 13, 13, 15, 15], [], []], intent='*BANDPASS*', solnorm=True,
         refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
         gainfield=['nearest', '', 'nearest'], append=True, minblperant=4)

# hifa_spwphaseup(pipelinemode="automatic")
#
gaincal(field='J2232+1143', minblperant=4, antenna='0~41', solint='inf',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_spwphaseup.s12_2.spw17_19_21_23.solintinf.gpcal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag'],
        minsnr=3,
        gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.channel.solintinf.bcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], []], intent='*BANDPASS*',
        solnorm=False,
        refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', ''])
gaincal(field='J2232+1143', minblperant=4, antenna='0~42', solint='inf',
        caltable='uid___A002_Xa4ce71_X1356.ms.hifa_spwphaseup.s12_4.spw17_19_21_23.solintinf.gpcal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag'],
        minsnr=3,
        gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.channel.solintinf.bcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa4ce71_X1356.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], []], intent='*BANDPASS*',
        solnorm=False,
        refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', ''])

# hifa_gfluxscale(pipelinemode="automatic")
#
# The absolute flux calibration is transferred to secondary calibrator
# sources.
#
gaincal(field='Ceres', minblperant=2,
        antenna='DV12,DV18,DA64,DA49,DA62,DA61,DA60,DA45,DA44,DV13,DA46,DA41,DV14,DA43,DA42,DV23,DA63,DV15,DV19,DV10,DV04,DV20,DA53,DA51,DV24,DV25,DA54,DA55,DV07,DA58,DA59,DV02,DV03,DV01,DV16,DV05&',
        solint='int',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_gfluxscale.s13_2.spw19_21_17_23.solintint.gpcal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
        'linear,linear'], minsnr=2.0,
        gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.channel.solintinf.bcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_spwphaseup.s12_2.spw17_19_21_23.solintinf.gpcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], []],
        intent='*FLUX*,*AMPLI*', solnorm=False, refant='DV19',
        gainfield=['nearest', '', '', 'nearest'], append=False)
gaincal(field='J0010+1058,J2232+1143', minblperant=4, antenna='0~41',
        solint='int',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_gfluxscale.s13_2.spw19_21_17_23.solintint.gpcal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
        'linear,linear'], minsnr=2.0,
        gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.channel.solintinf.bcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_spwphaseup.s12_2.spw17_19_21_23.solintinf.gpcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], []],
        intent='*PHASE*,*BANDPASS*', solnorm=False, refant='DV19',
        gainfield=['nearest', '', '', 'nearest'], append=True)
gaincal(field='Ceres,J0010+1058,J2232+1143', minblperant=2, antenna='0~41',
        solint='inf',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_gfluxscale.s13_4.spw19_21_17_23.solintinf.gacal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
        'linear,linear', 'linear,linear'], minsnr=2.0,
        gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.channel.solintinf.bcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_spwphaseup.s12_2.spw17_19_21_23.solintinf.gpcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_gfluxscale.s13_2.spw19_21_17_23.solintint.gpcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='a',
        gaintype='T', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], [], []],
        intent='*PHASE*,*FLUX*,*AMPLI*,*BANDPASS*', solnorm=False,
        refant='DV19', gainfield=['nearest', '', '', 'nearest', 'nearest'],
        append=False)
fluxscale(refspwmap=[-1], reference='Ceres',
          caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_gfluxscale.s13_4.spw19_21_17_23.solintinf.gacal.tbl',
          transfer='J0010+1058,J2232+1143', vis='uid___A002_Xa48b1f_X3ca7.ms',
          fluxtable='uid___A002_Xa48b1f_X3ca7.ms.hifa_gfluxscale.s13_5.fcal.tbl')
post_to_log(comment='Setjy marker: 2015-10-14 17:21:43.698123',
            echo_to_screen=False)
setjy(fluxdensity=[0.141297062006, 0.0, 0.0, 0.0], scalebychan=True,
      vis='uid___A002_Xa48b1f_X3ca7.ms', spix=0.0, spw='17', field='J0010+1058',
      reffreq='1GHz', intent='*PHASE*', selectdata=True, standard='manual',
      usescratch=True)
setjy(fluxdensity=[0.141521624491, 0.0, 0.0, 0.0], scalebychan=True,
      vis='uid___A002_Xa48b1f_X3ca7.ms', spix=0.0, spw='19', field='J0010+1058',
      reffreq='1GHz', intent='*PHASE*', selectdata=True, standard='manual',
      usescratch=True)
setjy(fluxdensity=[0.137566302974, 0.0, 0.0, 0.0], scalebychan=True,
      vis='uid___A002_Xa48b1f_X3ca7.ms', spix=0.0, spw='21', field='J0010+1058',
      reffreq='1GHz', intent='*PHASE*', selectdata=True, standard='manual',
      usescratch=True)
setjy(fluxdensity=[0.135419525848, 0.0, 0.0, 0.0], scalebychan=True,
      vis='uid___A002_Xa48b1f_X3ca7.ms', spix=0.0, spw='23', field='J0010+1058',
      reffreq='1GHz', intent='*PHASE*', selectdata=True, standard='manual',
      usescratch=True)
setjy(fluxdensity=[2.57918969552, 0.0, 0.0, 0.0], scalebychan=True,
      vis='uid___A002_Xa48b1f_X3ca7.ms', spix=0.0, spw='17', field='J2232+1143',
      reffreq='1GHz', intent='*BANDPASS*', selectdata=True, standard='manual',
      usescratch=True)
setjy(fluxdensity=[2.58134407495, 0.0, 0.0, 0.0], scalebychan=True,
      vis='uid___A002_Xa48b1f_X3ca7.ms', spix=0.0, spw='19', field='J2232+1143',
      reffreq='1GHz', intent='*BANDPASS*', selectdata=True, standard='manual',
      usescratch=True)
setjy(fluxdensity=[2.67676946041, 0.0, 0.0, 0.0], scalebychan=True,
      vis='uid___A002_Xa48b1f_X3ca7.ms', spix=0.0, spw='21', field='J2232+1143',
      reffreq='1GHz', intent='*BANDPASS*', selectdata=True, standard='manual',
      usescratch=True)
setjy(fluxdensity=[2.67561820974, 0.0, 0.0, 0.0], scalebychan=True,
      vis='uid___A002_Xa48b1f_X3ca7.ms', spix=0.0, spw='23', field='J2232+1143',
      reffreq='1GHz', intent='*BANDPASS*', selectdata=True, standard='manual',
      usescratch=True)
post_to_log(comment='Setjy marker: 2015-10-14 17:27:31.000126',
            echo_to_screen=False)
gaincal(field='Ceres', minblperant=2,
        antenna='DV19,DV18,DA64,DA49,DA62,DA61,DA60,DA45,DV10,DV13,DA46,DA41,DV14,DA43,DA42,DV23,DA63,DV21,DV04,DV20,DA53,DA50,DA51,DV24,DV25,DA54,DA55,DV15,DA58,DA59,DV02,DV03,DV01,DV16,DV05&',
        solint='int',
        caltable='uid___A002_Xa4ce71_X1356.ms.hifa_gfluxscale.s13_4.spw19_21_17_23.solintint.gpcal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
        'linear,linear'], minsnr=2.0,
        gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.channel.solintinf.bcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_spwphaseup.s12_4.spw17_19_21_23.solintinf.gpcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa4ce71_X1356.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], []],
        intent='*FLUX*,*AMPLI*', solnorm=False, refant='DA59',
        gainfield=['nearest', '', '', 'nearest'], append=False)
gaincal(field='J0010+1058,J2232+1143', minblperant=4, antenna='0~42',
        solint='int',
        caltable='uid___A002_Xa4ce71_X1356.ms.hifa_gfluxscale.s13_4.spw19_21_17_23.solintint.gpcal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
        'linear,linear'], minsnr=2.0,
        gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.channel.solintinf.bcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_spwphaseup.s12_4.spw17_19_21_23.solintinf.gpcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa4ce71_X1356.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], []],
        intent='*PHASE*,*BANDPASS*', solnorm=False, refant='DA59',
        gainfield=['nearest', '', '', 'nearest'], append=True)
gaincal(field='Ceres,J0010+1058,J2232+1143', minblperant=2, antenna='0~42',
        solint='inf',
        caltable='uid___A002_Xa4ce71_X1356.ms.hifa_gfluxscale.s13_6.spw19_21_17_23.solintinf.gacal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
        'linear,linear', 'linear,linear'], minsnr=2.0,
        gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.channel.solintinf.bcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_spwphaseup.s12_4.spw17_19_21_23.solintinf.gpcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_gfluxscale.s13_4.spw19_21_17_23.solintint.gpcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa4ce71_X1356.ms', calmode='a',
        gaintype='T', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], [], []],
        intent='*PHASE*,*FLUX*,*AMPLI*,*BANDPASS*', solnorm=False,
        refant='DA59', gainfield=['nearest', '', '', 'nearest', 'nearest'],
        append=False)
fluxscale(refspwmap=[-1], reference='Ceres',
          caltable='uid___A002_Xa4ce71_X1356.ms.hifa_gfluxscale.s13_6.spw19_21_17_23.solintinf.gacal.tbl',
          transfer='J0010+1058,J2232+1143', vis='uid___A002_Xa4ce71_X1356.ms',
          fluxtable='uid___A002_Xa4ce71_X1356.ms.hifa_gfluxscale.s13_7.fcal.tbl')
post_to_log(comment='Setjy marker: 2015-10-14 17:34:28.399056',
            echo_to_screen=False)
setjy(fluxdensity=[0.143468931805, 0.0, 0.0, 0.0], scalebychan=True,
      vis='uid___A002_Xa4ce71_X1356.ms', spix=0.0, spw='17', field='J0010+1058',
      reffreq='1GHz', intent='*PHASE*', selectdata=True, standard='manual',
      usescratch=True)
setjy(fluxdensity=[0.145262005952, 0.0, 0.0, 0.0], scalebychan=True,
      vis='uid___A002_Xa4ce71_X1356.ms', spix=0.0, spw='19', field='J0010+1058',
      reffreq='1GHz', intent='*PHASE*', selectdata=True, standard='manual',
      usescratch=True)
setjy(fluxdensity=[0.141250115564, 0.0, 0.0, 0.0], scalebychan=True,
      vis='uid___A002_Xa4ce71_X1356.ms', spix=0.0, spw='21', field='J0010+1058',
      reffreq='1GHz', intent='*PHASE*', selectdata=True, standard='manual',
      usescratch=True)
setjy(fluxdensity=[0.139784225247, 0.0, 0.0, 0.0], scalebychan=True,
      vis='uid___A002_Xa4ce71_X1356.ms', spix=0.0, spw='23', field='J0010+1058',
      reffreq='1GHz', intent='*PHASE*', selectdata=True, standard='manual',
      usescratch=True)
setjy(fluxdensity=[2.58024150078, 0.0, 0.0, 0.0], scalebychan=True,
      vis='uid___A002_Xa4ce71_X1356.ms', spix=0.0, spw='17', field='J2232+1143',
      reffreq='1GHz', intent='*BANDPASS*', selectdata=True, standard='manual',
      usescratch=True)
setjy(fluxdensity=[2.60086227022, 0.0, 0.0, 0.0], scalebychan=True,
      vis='uid___A002_Xa4ce71_X1356.ms', spix=0.0, spw='19', field='J2232+1143',
      reffreq='1GHz', intent='*BANDPASS*', selectdata=True, standard='manual',
      usescratch=True)
setjy(fluxdensity=[2.71916266484, 0.0, 0.0, 0.0], scalebychan=True,
      vis='uid___A002_Xa4ce71_X1356.ms', spix=0.0, spw='21', field='J2232+1143',
      reffreq='1GHz', intent='*BANDPASS*', selectdata=True, standard='manual',
      usescratch=True)
setjy(fluxdensity=[2.71527903475, 0.0, 0.0, 0.0], scalebychan=True,
      vis='uid___A002_Xa4ce71_X1356.ms', spix=0.0, spw='23', field='J2232+1143',
      reffreq='1GHz', intent='*BANDPASS*', selectdata=True, standard='manual',
      usescratch=True)
post_to_log(comment='Setjy marker: 2015-10-14 17:41:01.058766',
            echo_to_screen=False)

# hifa_timegaincal(pipelinemode="automatic")
#
# Time dependent gain calibrations are computed.
#
gaincal(field='Ceres,J0010+1058,J2232+1143', minblperant=4, antenna='0~41',
        solint='int',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_timegaincal.s14_2.spw17_19_21_23.solintint.gacal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
        'linear,linear'], minsnr=2.0,
        gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.channel.solintinf.bcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_spwphaseup.s12_2.spw17_19_21_23.solintinf.gpcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='a',
        gaintype='T', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], []],
        intent='*PHASE*,*FLUX*,*AMPLI*,*BANDPASS*', solnorm=False,
        refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', '', 'nearest'])
gaincal(field='Ceres,J0010+1058,J2232+1143', minblperant=4, antenna='0~41',
        solint='inf',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_timegaincal.s14_3.spw17_19_21_23.solintinf.gpcal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
        'linear,linear'], minsnr=3.0,
        gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.channel.solintinf.bcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_spwphaseup.s12_2.spw17_19_21_23.solintinf.gpcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], []],
        intent='*PHASE*,*FLUX*,*AMPLI*,*BANDPASS*', solnorm=False,
        refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', '', 'nearest'])
gaincal(field='Ceres,J0010+1058,J2232+1143', minblperant=4, antenna='0~41',
        solint='int',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_timegaincal.s14_4.spw17_19_21_23.solintint.gpcal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
        'linear,linear'], minsnr=2.0,
        gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.channel.solintinf.bcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_spwphaseup.s12_2.spw17_19_21_23.solintinf.gpcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], []],
        intent='*PHASE*,*FLUX*,*AMPLI*,*BANDPASS*', solnorm=False,
        refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', '', 'nearest'])
gaincal(field='Ceres,J0010+1058,J2232+1143', minblperant=4, antenna='0~41',
        solint='inf',
        caltable='uid___A002_Xa48b1f_X3ca7.ms.hifa_timegaincal.s14_5.spw17_19_21_23.solintinf.gacal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
        'linear,linear', 'linear,linear'], minsnr=3.0,
        gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.channel.solintinf.bcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_spwphaseup.s12_2.spw17_19_21_23.solintinf.gpcal.tbl',
        'uid___A002_Xa48b1f_X3ca7.ms.hifa_timegaincal.s14_4.spw17_19_21_23.solintint.gpcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa48b1f_X3ca7.ms', calmode='a',
        gaintype='T', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], [], []],
        intent='*PHASE*,*FLUX*,*AMPLI*,*BANDPASS*', solnorm=False,
        refant='DV19,DA49,DV04,DV18,DA55,DA53,DA63,DA41,DV01,DV13,DV15,DA61,DA43,DA42,DV24,DV25,DV14,DA46,DV16,DV23,DV20,DA51,DA58,DA60,DA54,DV02,DV12,DV05,DA62,DV10,DA59,DA47,DA44,DA45,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', '', 'nearest', 'nearest'])
gaincal(field='Ceres,J0010+1058,J2232+1143', minblperant=4, antenna='0~42',
        solint='int',
        caltable='uid___A002_Xa4ce71_X1356.ms.hifa_timegaincal.s14_4.spw17_19_21_23.solintint.gacal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
        'linear,linear'], minsnr=2.0,
        gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.channel.solintinf.bcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_spwphaseup.s12_4.spw17_19_21_23.solintinf.gpcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa4ce71_X1356.ms', calmode='a',
        gaintype='T', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], []],
        intent='*PHASE*,*FLUX*,*AMPLI*,*BANDPASS*', solnorm=False,
        refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', '', 'nearest'])
gaincal(field='Ceres,J0010+1058,J2232+1143', minblperant=4, antenna='0~42',
        solint='inf',
        caltable='uid___A002_Xa4ce71_X1356.ms.hifa_timegaincal.s14_5.spw17_19_21_23.solintinf.gpcal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
        'linear,linear'], minsnr=3.0,
        gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.channel.solintinf.bcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_spwphaseup.s12_4.spw17_19_21_23.solintinf.gpcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa4ce71_X1356.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], []],
        intent='*PHASE*,*FLUX*,*AMPLI*,*BANDPASS*', solnorm=False,
        refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', '', 'nearest'])
gaincal(field='Ceres,J0010+1058,J2232+1143', minblperant=4, antenna='0~42',
        solint='int',
        caltable='uid___A002_Xa4ce71_X1356.ms.hifa_timegaincal.s14_6.spw17_19_21_23.solintint.gpcal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
        'linear,linear'], minsnr=2.0,
        gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.channel.solintinf.bcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_spwphaseup.s12_4.spw17_19_21_23.solintinf.gpcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa4ce71_X1356.ms', calmode='p',
        gaintype='G', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], []],
        intent='*PHASE*,*FLUX*,*AMPLI*,*BANDPASS*', solnorm=False,
        refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', '', 'nearest'])
gaincal(field='Ceres,J0010+1058,J2232+1143', minblperant=4, antenna='0~42',
        solint='inf',
        caltable='uid___A002_Xa4ce71_X1356.ms.hifa_timegaincal.s14_7.spw17_19_21_23.solintinf.gacal.tbl',
        interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
        'linear,linear', 'linear,linear'], minsnr=3.0,
        gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.channel.solintinf.bcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_spwphaseup.s12_4.spw17_19_21_23.solintinf.gpcal.tbl',
        'uid___A002_Xa4ce71_X1356.ms.hifa_timegaincal.s14_6.spw17_19_21_23.solintint.gpcal.tbl'],
        spw='17,19,21,23', vis='uid___A002_Xa4ce71_X1356.ms', calmode='a',
        gaintype='T', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13,
        15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], [], []],
        intent='*PHASE*,*FLUX*,*AMPLI*,*BANDPASS*', solnorm=False,
        refant='DA59,DV19,DA49,DV04,DV18,DA46,DA50,DA53,DA63,DA41,DV01,DV13,DA61,DV15,DV16,DV24,DV25,DV14,DV05,DV23,DV20,DA51,DA42,DA58,DA54,DA60,DV02,DV21,DA62,DV10,DA47,DA45,DA44,DV03,DV17,DA52,DA64,DV07,DV22,DA57,DV11',
        gainfield=['nearest', '', '', 'nearest', 'nearest'])

# hif_applycal(pipelinemode="automatic")
#
# Calibrations are applied  to the data. Final flagging summaries are computed
#
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms', mode='summary')
applycal(gainfield=['nearest', '', '', 'nearest', 'nearest', 'nearest'],
         flagbackup=True, vis='uid___A002_Xa48b1f_X3ca7.ms',
         interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
         'linear,linear', 'linear,linear', 'linear,linear'],
         gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.channel.solintinf.bcal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_spwphaseup.s12_2.spw17_19_21_23.solintinf.gpcal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_timegaincal.s14_3.spw17_19_21_23.solintinf.gpcal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_timegaincal.s14_5.spw17_19_21_23.solintinf.gacal.tbl'],
         spw='17,19,21,23', calwt=[True, False, True, False, False, True],
         field='BX610,J0010+1058,J0019+2021', applymode='calflagstrict',
         antenna='*&*', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13,
         13, 15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], [], [], []],
         intent='*PHASE*,*DELAY*,*TARGET*')
applycal(gainfield=['nearest', '', '', 'nearest', 'nearest', 'nearest'],
         flagbackup=True, vis='uid___A002_Xa48b1f_X3ca7.ms',
         interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
         'linear,linear', 'linear,linear', 'linear,linear'],
         gaintable=['uid___A002_Xa48b1f_X3ca7.ms.hifa_tsyscal.s6_1.tsyscal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_wvrgcalflag.s8_4.sm6_048s.wvrcal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_bandpass.s11_3.spw17_19_21_23.channel.solintinf.bcal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_spwphaseup.s12_2.spw17_19_21_23.solintinf.gpcal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_timegaincal.s14_4.spw17_19_21_23.solintint.gpcal.tbl',
         'uid___A002_Xa48b1f_X3ca7.ms.hifa_timegaincal.s14_5.spw17_19_21_23.solintinf.gacal.tbl'],
         spw='17,19,21,23', calwt=[True, False, True, False, False, True],
         field='Ceres,J2232+1143', applymode='calflagstrict', antenna='*&*',
         spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
         11, 11, 13, 13, 15, 15], [], [], [], [], []],
         intent='*FLUX*,*AMPLI*,*BANDPASS*')
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms', mode='summary')
flagdata(vis='uid___A002_Xa48b1f_X3ca7.ms', mode='list', inpfile=["field='0'
         spw='17' mode='summary' name='AntSpw017Field0'", "field='0' spw='19'
         mode='summary' name='AntSpw019Field0'", "field='0' spw='21'
         mode='summary' name='AntSpw021Field0'", "field='0' spw='23'
         mode='summary' name='AntSpw023Field0'", "field='2' spw='17'
         mode='summary' name='AntSpw017Field2'", "field='2' spw='19'
         mode='summary' name='AntSpw019Field2'", "field='2' spw='21'
         mode='summary' name='AntSpw021Field2'", "field='2' spw='23'
         mode='summary' name='AntSpw023Field2'", "field='3' spw='17'
         mode='summary' name='AntSpw017Field3'", "field='3' spw='19'
         mode='summary' name='AntSpw019Field3'", "field='3' spw='21'
         mode='summary' name='AntSpw021Field3'", "field='3' spw='23'
         mode='summary' name='AntSpw023Field3'", "field='4' spw='17'
         mode='summary' name='AntSpw017Field4'", "field='4' spw='19'
         mode='summary' name='AntSpw019Field4'", "field='4' spw='21'
         mode='summary' name='AntSpw021Field4'", "field='4' spw='23'
         mode='summary' name='AntSpw023Field4'", "field='5' spw='17'
         mode='summary' name='AntSpw017Field5'", "field='5' spw='19'
         mode='summary' name='AntSpw019Field5'", "field='5' spw='21'
         mode='summary' name='AntSpw021Field5'", "field='5' spw='23'
         mode='summary' name='AntSpw023Field5'"])
flagdata(vis='uid___A002_Xa4ce71_X1356.ms', mode='summary')
applycal(gainfield=['nearest', '', '', 'nearest', 'nearest', 'nearest'],
         flagbackup=True, vis='uid___A002_Xa4ce71_X1356.ms',
         interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
         'linear,linear', 'linear,linear', 'linear,linear'],
         gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.channel.solintinf.bcal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_spwphaseup.s12_4.spw17_19_21_23.solintinf.gpcal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_timegaincal.s14_5.spw17_19_21_23.solintinf.gpcal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_timegaincal.s14_7.spw17_19_21_23.solintinf.gacal.tbl'],
         spw='17,19,21,23', calwt=[True, False, True, False, False, True],
         field='BX610,J0010+1058,J0019+2021', applymode='calflagstrict',
         antenna='*&*', spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13,
         13, 15, 15, 9, 9, 11, 11, 13, 13, 15, 15], [], [], [], [], []],
         intent='*PHASE*,*DELAY*,*TARGET*')
applycal(gainfield=['nearest', '', '', 'nearest', 'nearest', 'nearest'],
         flagbackup=True, vis='uid___A002_Xa4ce71_X1356.ms',
         interp=['linear,linear', 'nearest', 'linearperobs,linearflag',
         'linear,linear', 'linear,linear', 'linear,linear'],
         gaintable=['uid___A002_Xa4ce71_X1356.ms.hifa_tsyscal.s6_3.tsyscal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_wvrgcalflag.s8_8.sm6_048s.wvrcal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_bandpass.s11_5.spw17_19_21_23.channel.solintinf.bcal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_spwphaseup.s12_4.spw17_19_21_23.solintinf.gpcal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_timegaincal.s14_6.spw17_19_21_23.solintint.gpcal.tbl',
         'uid___A002_Xa4ce71_X1356.ms.hifa_timegaincal.s14_7.spw17_19_21_23.solintinf.gacal.tbl'],
         spw='17,19,21,23', calwt=[True, False, True, False, False, True],
         field='Ceres,J2232+1143', applymode='calflagstrict', antenna='*&*',
         spwmap=[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 11, 11, 13, 13, 15, 15, 9, 9,
         11, 11, 13, 13, 15, 15], [], [], [], [], []],
         intent='*FLUX*,*AMPLI*,*BANDPASS*')
flagdata(vis='uid___A002_Xa4ce71_X1356.ms', mode='summary')
flagdata(vis='uid___A002_Xa4ce71_X1356.ms', mode='list', inpfile=["field='0'
         spw='17' mode='summary' name='AntSpw017Field0'", "field='0' spw='19'
         mode='summary' name='AntSpw019Field0'", "field='0' spw='21'
         mode='summary' name='AntSpw021Field0'", "field='0' spw='23'
         mode='summary' name='AntSpw023Field0'", "field='2' spw='17'
         mode='summary' name='AntSpw017Field2'", "field='2' spw='19'
         mode='summary' name='AntSpw019Field2'", "field='2' spw='21'
         mode='summary' name='AntSpw021Field2'", "field='2' spw='23'
         mode='summary' name='AntSpw023Field2'", "field='3' spw='17'
         mode='summary' name='AntSpw017Field3'", "field='3' spw='19'
         mode='summary' name='AntSpw019Field3'", "field='3' spw='21'
         mode='summary' name='AntSpw021Field3'", "field='3' spw='23'
         mode='summary' name='AntSpw023Field3'", "field='4' spw='17'
         mode='summary' name='AntSpw017Field4'", "field='4' spw='19'
         mode='summary' name='AntSpw019Field4'", "field='4' spw='21'
         mode='summary' name='AntSpw021Field4'", "field='4' spw='23'
         mode='summary' name='AntSpw023Field4'", "field='5' spw='17'
         mode='summary' name='AntSpw017Field5'", "field='5' spw='19'
         mode='summary' name='AntSpw019Field5'", "field='5' spw='21'
         mode='summary' name='AntSpw021Field5'", "field='5' spw='23'
         mode='summary' name='AntSpw023Field5'"])

# hif_makecleanlist(intent='PHASE,BANDPASS,CHECK')
#
# A list of target sources to be imaged is constructed.
#

# hif_cleanlist(pipelinemode="automatic")
#
# A list of target sources is cleaned.
#
clean(phasecenter='ICRS 00:19:37.853 +020.21.45.66', scan=['11, 18, 25, 32, 39',
      '11, 18, 25, 32, 39'], spw='17', vis=['uid___A002_Xa48b1f_X3ca7.ms',
      'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0019+2021_chk.spw17.Q.iter0',
      threshold='0.0mJy', imsize=[1500, 1500], npixels=0, cell=['0.042arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='Q',
      intent='*DELAY*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:19:37.853 +020.21.45.66', scan=['11, 18, 25, 32, 39',
      '11, 18, 25, 32, 39'], spw='17', vis=['uid___A002_Xa48b1f_X3ca7.ms',
      'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0019+2021_chk.spw17.I.iter0',
      threshold='0.0mJy', imsize=[1500, 1500], npixels=0, cell=['0.042arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='I',
      intent='*DELAY*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:19:37.853 +020.21.45.66', scan=['11, 18, 25, 32, 39',
      '11, 18, 25, 32, 39'], spw='17', vis=['uid___A002_Xa48b1f_X3ca7.ms',
      'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0019+2021_chk.spw17.I.iter1',
      threshold='0.000217767737922Jy', imsize=[1500, 1500], npixels=0,
      cell=['0.042arcsec'], outframe='LSRK', usescratch=True, noise='1.0Jy',
      stokes='I', intent='*DELAY*', robust=0.0, niter=1000, nchan=-1,
      imagermode='csclean', weighting='natural',
      mask='uid___A001_X12b_X23b.s16_0.J0019+2021_chk.spw17.I.iter1.cleanmask',
      mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:19:37.853 +020.21.45.66', scan=['11, 18, 25, 32, 39',
      '11, 18, 25, 32, 39'], spw='19', vis=['uid___A002_Xa48b1f_X3ca7.ms',
      'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0019+2021_chk.spw19.Q.iter0',
      threshold='0.0mJy', imsize=[1458, 1458], npixels=0, cell=['0.042arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='Q',
      intent='*DELAY*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:19:37.853 +020.21.45.66', scan=['11, 18, 25, 32, 39',
      '11, 18, 25, 32, 39'], spw='19', vis=['uid___A002_Xa48b1f_X3ca7.ms',
      'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0019+2021_chk.spw19.I.iter0',
      threshold='0.0mJy', imsize=[1458, 1458], npixels=0, cell=['0.042arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='I',
      intent='*DELAY*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:19:37.853 +020.21.45.66', scan=['11, 18, 25, 32, 39',
      '11, 18, 25, 32, 39'], spw='19', vis=['uid___A002_Xa48b1f_X3ca7.ms',
      'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0019+2021_chk.spw19.I.iter1',
      threshold='0.000230392135563Jy', imsize=[1458, 1458], npixels=0,
      cell=['0.042arcsec'], outframe='LSRK', usescratch=True, noise='1.0Jy',
      stokes='I', intent='*DELAY*', robust=0.0, niter=1000, nchan=-1,
      imagermode='csclean', weighting='natural',
      mask='uid___A001_X12b_X23b.s16_0.J0019+2021_chk.spw19.I.iter1.cleanmask',
      mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:19:37.853 +020.21.45.66', scan=['11, 18, 25, 32, 39',
      '11, 18, 25, 32, 39'], spw='21', vis=['uid___A002_Xa48b1f_X3ca7.ms',
      'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0019+2021_chk.spw21.Q.iter0',
      threshold='0.0mJy', imsize=[1458, 1458], npixels=0, cell=['0.045arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='Q',
      intent='*DELAY*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:19:37.853 +020.21.45.66', scan=['11, 18, 25, 32, 39',
      '11, 18, 25, 32, 39'], spw='21', vis=['uid___A002_Xa48b1f_X3ca7.ms',
      'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0019+2021_chk.spw21.I.iter0',
      threshold='0.0mJy', imsize=[1458, 1458], npixels=0, cell=['0.045arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='I',
      intent='*DELAY*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:19:37.853 +020.21.45.66', scan=['11, 18, 25, 32, 39',
      '11, 18, 25, 32, 39'], spw='21', vis=['uid___A002_Xa48b1f_X3ca7.ms',
      'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0019+2021_chk.spw21.I.iter1',
      threshold='0.000206272117794Jy', imsize=[1458, 1458], npixels=0,
      cell=['0.045arcsec'], outframe='LSRK', usescratch=True, noise='1.0Jy',
      stokes='I', intent='*DELAY*', robust=0.0, niter=1000, nchan=-1,
      imagermode='csclean', weighting='natural',
      mask='uid___A001_X12b_X23b.s16_0.J0019+2021_chk.spw21.I.iter1.cleanmask',
      mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:19:37.853 +020.21.45.66', scan=['11, 18, 25, 32, 39',
      '11, 18, 25, 32, 39'], spw='23', vis=['uid___A002_Xa48b1f_X3ca7.ms',
      'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0019+2021_chk.spw23.Q.iter0',
      threshold='0.0mJy', imsize=[1440, 1440], npixels=0, cell=['0.046arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='Q',
      intent='*DELAY*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:19:37.853 +020.21.45.66', scan=['11, 18, 25, 32, 39',
      '11, 18, 25, 32, 39'], spw='23', vis=['uid___A002_Xa48b1f_X3ca7.ms',
      'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0019+2021_chk.spw23.I.iter0',
      threshold='0.0mJy', imsize=[1440, 1440], npixels=0, cell=['0.046arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='I',
      intent='*DELAY*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:19:37.853 +020.21.45.66', scan=['11, 18, 25, 32, 39',
      '11, 18, 25, 32, 39'], spw='23', vis=['uid___A002_Xa48b1f_X3ca7.ms',
      'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0019+2021_chk.spw23.I.iter1',
      threshold='0.00021595673752Jy', imsize=[1440, 1440], npixels=0,
      cell=['0.046arcsec'], outframe='LSRK', usescratch=True, noise='1.0Jy',
      stokes='I', intent='*DELAY*', robust=0.0, niter=1000, nchan=-1,
      imagermode='csclean', weighting='natural',
      mask='uid___A001_X12b_X23b.s16_0.J0019+2021_chk.spw23.I.iter1.cleanmask',
      mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:10:31.005 +010.58.29.52', scan=['9, 14, 16, 21, 23,
      28, 30, 35, 37, 42', '9, 14, 16, 21, 23, 28, 30, 35, 37, 42'], spw='17',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0010+1058_ph.spw17.Q.iter0',
      threshold='0.0mJy', imsize=[300, 300], npixels=0, cell=['0.042arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='Q',
      intent='*PHASE*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:10:31.005 +010.58.29.52', scan=['9, 14, 16, 21, 23,
      28, 30, 35, 37, 42', '9, 14, 16, 21, 23, 28, 30, 35, 37, 42'], spw='17',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0010+1058_ph.spw17.I.iter0',
      threshold='0.0mJy', imsize=[300, 300], npixels=0, cell=['0.042arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='I',
      intent='*PHASE*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:10:31.005 +010.58.29.52', scan=['9, 14, 16, 21, 23,
      28, 30, 35, 37, 42', '9, 14, 16, 21, 23, 28, 30, 35, 37, 42'], spw='17',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0010+1058_ph.spw17.I.iter1',
      threshold='0.000125305072288Jy', imsize=[300, 300], npixels=0,
      cell=['0.042arcsec'], outframe='LSRK', usescratch=True, noise='1.0Jy',
      stokes='I', intent='*PHASE*', robust=0.0, niter=1000, nchan=-1,
      imagermode='csclean', weighting='natural',
      mask='uid___A001_X12b_X23b.s16_0.J0010+1058_ph.spw17.I.iter1.cleanmask',
      mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:10:31.005 +010.58.29.52', scan=['9, 14, 16, 21, 23,
      28, 30, 35, 37, 42', '9, 14, 16, 21, 23, 28, 30, 35, 37, 42'], spw='19',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0010+1058_ph.spw19.Q.iter0',
      threshold='0.0mJy', imsize=[300, 300], npixels=0, cell=['0.042arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='Q',
      intent='*PHASE*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:10:31.005 +010.58.29.52', scan=['9, 14, 16, 21, 23,
      28, 30, 35, 37, 42', '9, 14, 16, 21, 23, 28, 30, 35, 37, 42'], spw='19',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0010+1058_ph.spw19.I.iter0',
      threshold='0.0mJy', imsize=[300, 300], npixels=0, cell=['0.042arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='I',
      intent='*PHASE*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:10:31.005 +010.58.29.52', scan=['9, 14, 16, 21, 23,
      28, 30, 35, 37, 42', '9, 14, 16, 21, 23, 28, 30, 35, 37, 42'], spw='19',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0010+1058_ph.spw19.I.iter1',
      threshold='0.00013690830383Jy', imsize=[300, 300], npixels=0,
      cell=['0.042arcsec'], outframe='LSRK', usescratch=True, noise='1.0Jy',
      stokes='I', intent='*PHASE*', robust=0.0, niter=1000, nchan=-1,
      imagermode='csclean', weighting='natural',
      mask='uid___A001_X12b_X23b.s16_0.J0010+1058_ph.spw19.I.iter1.cleanmask',
      mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:10:31.005 +010.58.29.52', scan=['9, 14, 16, 21, 23,
      28, 30, 35, 37, 42', '9, 14, 16, 21, 23, 28, 30, 35, 37, 42'], spw='21',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0010+1058_ph.spw21.Q.iter0',
      threshold='0.0mJy', imsize=[300, 300], npixels=0, cell=['0.045arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='Q',
      intent='*PHASE*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:10:31.005 +010.58.29.52', scan=['9, 14, 16, 21, 23,
      28, 30, 35, 37, 42', '9, 14, 16, 21, 23, 28, 30, 35, 37, 42'], spw='21',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0010+1058_ph.spw21.I.iter0',
      threshold='0.0mJy', imsize=[300, 300], npixels=0, cell=['0.045arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='I',
      intent='*PHASE*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:10:31.005 +010.58.29.52', scan=['9, 14, 16, 21, 23,
      28, 30, 35, 37, 42', '9, 14, 16, 21, 23, 28, 30, 35, 37, 42'], spw='21',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0010+1058_ph.spw21.I.iter1',
      threshold='0.000118103795103Jy', imsize=[300, 300], npixels=0,
      cell=['0.045arcsec'], outframe='LSRK', usescratch=True, noise='1.0Jy',
      stokes='I', intent='*PHASE*', robust=0.0, niter=1000, nchan=-1,
      imagermode='csclean', weighting='natural',
      mask='uid___A001_X12b_X23b.s16_0.J0010+1058_ph.spw21.I.iter1.cleanmask',
      mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:10:31.005 +010.58.29.52', scan=['9, 14, 16, 21, 23,
      28, 30, 35, 37, 42', '9, 14, 16, 21, 23, 28, 30, 35, 37, 42'], spw='23',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0010+1058_ph.spw23.Q.iter0',
      threshold='0.0mJy', imsize=[300, 300], npixels=0, cell=['0.046arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='Q',
      intent='*PHASE*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:10:31.005 +010.58.29.52', scan=['9, 14, 16, 21, 23,
      28, 30, 35, 37, 42', '9, 14, 16, 21, 23, 28, 30, 35, 37, 42'], spw='23',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0010+1058_ph.spw23.I.iter0',
      threshold='0.0mJy', imsize=[300, 300], npixels=0, cell=['0.046arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='I',
      intent='*PHASE*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 00:10:31.005 +010.58.29.52', scan=['9, 14, 16, 21, 23,
      28, 30, 35, 37, 42', '9, 14, 16, 21, 23, 28, 30, 35, 37, 42'], spw='23',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J0010+1058_ph.spw23.I.iter1',
      threshold='0.000118782721984Jy', imsize=[300, 300], npixels=0,
      cell=['0.046arcsec'], outframe='LSRK', usescratch=True, noise='1.0Jy',
      stokes='I', intent='*PHASE*', robust=0.0, niter=1000, nchan=-1,
      imagermode='csclean', weighting='natural',
      mask='uid___A001_X12b_X23b.s16_0.J0010+1058_ph.spw23.I.iter1.cleanmask',
      mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 22:32:36.408 +011.43.50.92', scan=['4', '4'], spw='17',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J2232+1143_bp.spw17.Q.iter0',
      threshold='0.0mJy', imsize=[300, 300], npixels=0, cell=['0.042arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='Q',
      intent='*BANDPASS*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 22:32:36.408 +011.43.50.92', scan=['4', '4'], spw='17',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J2232+1143_bp.spw17.I.iter0',
      threshold='0.0mJy', imsize=[300, 300], npixels=0, cell=['0.042arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='I',
      intent='*BANDPASS*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 22:32:36.408 +011.43.50.92', scan=['4', '4'], spw='17',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J2232+1143_bp.spw17.I.iter1',
      threshold='0.00199127476662Jy', imsize=[300, 300], npixels=0,
      cell=['0.042arcsec'], outframe='LSRK', usescratch=True, noise='1.0Jy',
      stokes='I', intent='*BANDPASS*', robust=0.0, niter=1000, nchan=-1,
      imagermode='csclean', weighting='natural',
      mask='uid___A001_X12b_X23b.s16_0.J2232+1143_bp.spw17.I.iter1.cleanmask',
      mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 22:32:36.408 +011.43.50.92', scan=['4', '4'], spw='19',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J2232+1143_bp.spw19.Q.iter0',
      threshold='0.0mJy', imsize=[300, 300], npixels=0, cell=['0.042arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='Q',
      intent='*BANDPASS*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 22:32:36.408 +011.43.50.92', scan=['4', '4'], spw='19',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J2232+1143_bp.spw19.I.iter0',
      threshold='0.0mJy', imsize=[300, 300], npixels=0, cell=['0.042arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='I',
      intent='*BANDPASS*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 22:32:36.408 +011.43.50.92', scan=['4', '4'], spw='19',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J2232+1143_bp.spw19.I.iter1',
      threshold='0.00192540162243Jy', imsize=[300, 300], npixels=0,
      cell=['0.042arcsec'], outframe='LSRK', usescratch=True, noise='1.0Jy',
      stokes='I', intent='*BANDPASS*', robust=0.0, niter=1000, nchan=-1,
      imagermode='csclean', weighting='natural',
      mask='uid___A001_X12b_X23b.s16_0.J2232+1143_bp.spw19.I.iter1.cleanmask',
      mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 22:32:36.408 +011.43.50.92', scan=['4', '4'], spw='21',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J2232+1143_bp.spw21.Q.iter0',
      threshold='0.0mJy', imsize=[300, 300], npixels=0, cell=['0.045arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='Q',
      intent='*BANDPASS*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 22:32:36.408 +011.43.50.92', scan=['4', '4'], spw='21',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J2232+1143_bp.spw21.I.iter0',
      threshold='0.0mJy', imsize=[300, 300], npixels=0, cell=['0.045arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='I',
      intent='*BANDPASS*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 22:32:36.408 +011.43.50.92', scan=['4', '4'], spw='21',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J2232+1143_bp.spw21.I.iter1',
      threshold='0.00214374251664Jy', imsize=[300, 300], npixels=0,
      cell=['0.045arcsec'], outframe='LSRK', usescratch=True, noise='1.0Jy',
      stokes='I', intent='*BANDPASS*', robust=0.0, niter=1000, nchan=-1,
      imagermode='csclean', weighting='natural',
      mask='uid___A001_X12b_X23b.s16_0.J2232+1143_bp.spw21.I.iter1.cleanmask',
      mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 22:32:36.408 +011.43.50.92', scan=['4', '4'], spw='23',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J2232+1143_bp.spw23.Q.iter0',
      threshold='0.0mJy', imsize=[300, 300], npixels=0, cell=['0.046arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='Q',
      intent='*BANDPASS*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 22:32:36.408 +011.43.50.92', scan=['4', '4'], spw='23',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J2232+1143_bp.spw23.I.iter0',
      threshold='0.0mJy', imsize=[300, 300], npixels=0, cell=['0.046arcsec'],
      outframe='LSRK', usescratch=True, noise='1.0Jy', stokes='I',
      intent='*BANDPASS*', robust=0.0, niter=0, nchan=-1, imagermode='csclean',
      weighting='natural', mode='mfs', selectdata=True, interactive=False)
clean(phasecenter='ICRS 22:32:36.408 +011.43.50.92', scan=['4', '4'], spw='23',
      vis=['uid___A002_Xa48b1f_X3ca7.ms', 'uid___A002_Xa4ce71_X1356.ms'],
      imagename='uid___A001_X12b_X23b.s16_0.J2232+1143_bp.spw23.I.iter1',
      threshold='0.00225612940267Jy', imsize=[300, 300], npixels=0,
      cell=['0.046arcsec'], outframe='LSRK', usescratch=True, noise='1.0Jy',
      stokes='I', intent='*BANDPASS*', robust=0.0, niter=1000, nchan=-1,
      imagermode='csclean', weighting='natural',
      mask='uid___A001_X12b_X23b.s16_0.J2232+1143_bp.spw23.I.iter1.cleanmask',
      mode='mfs', selectdata=True, interactive=False)

# hif_exportdata(pipelinemode="automatic")
#
# The output data products are computed.
#
flagmanager(vis='uid___A002_Xa48b1f_X3ca7.ms', mode='save',
            versionname='Pipeline_Final')
flagmanager(vis='uid___A002_Xa4ce71_X1356.ms', mode='save',
            versionname='Pipeline_Final')
